# Generated by Django 4.0.4 on 2022-07-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Instrumento de cuerda', (('Guitarras', 'Guitarras'), ('Bajos', 'Bajos'), ('Pianos', 'Pianos'))), ('Percusion', (('Baterias Acusticas', 'Baterias Acusticas'), ('Bateria Electronica', 'Bateria Electronica'))), ('Amplificadores', (('Cabezales', 'Cabezales'), ('Cajas', 'Cajas'))), ('Accesorios varios', 'Accesorios varios')], max_length=25, null=True),
        ),
    ]
