# Generated by Django 4.0.4 on 2022-07-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_carroproductos_pedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Pedidos',
        ),
    ]
