# Generated by Django 4.0.4 on 2022-07-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_carropedido_alter_pedidos_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarroPedido',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='productos',
            field=models.ManyToManyField(to='api.carroproductos'),
        ),
    ]
