# Generated by Django 4.0.4 on 2022-07-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_carropedido_alter_pedidos_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='productos',
            field=models.ManyToManyField(to='api.producto'),
        ),
    ]
