# Generated by Django 4.0.4 on 2022-07-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_producto_stock_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=35)),
                ('total', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('valor_total', models.IntegerField()),
                ('estado', models.CharField(max_length=25)),
                ('productos', models.ManyToManyField(to='api.carroproductos')),
            ],
        ),
    ]
