# Generated by Django 4.0.4 on 2022-07-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_pedido_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productoId', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=35)),
                ('total', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='productos',
            field=models.ManyToManyField(to='api.carropedido'),
        ),
    ]
