# Generated by Django 4.0.4 on 2022-07-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pedidos_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='productos',
            field=models.ManyToManyField(to='api.carroproductos'),
        ),
    ]
