# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT1Agregaralcarrito():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t1Agregaralcarrito(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.LINK_TEXT, "Productos").click()
    self.driver.find_element(By.LINK_TEXT, "Agregar al carro").click()
    assert self.driver.find_element(By.ID, "nombre").text == "Guitarra Vizcaya Castilla"
    elements = self.driver.find_elements(By.ID, "cantidad")
    assert len(elements) > 0
    self.driver.close()
  
